### ISSUE TITLE
error on `ESM` environment

### ISSUE THREAD

**Issue by userquin** [antfu/vite-plugin-inspect#13]
context: https://github.com/antfu/unplugin-auto-import/issues/79#issuecomment-977159278

```bash
failed to load config from C:\Users\joshua\test\vite.config.ts
Error: Dynamic require of "os" is not supported
    at __require (file:///C:/Users/joshua/test/node_modules/vite-plugin-inspect/dist/index.mjs:26:9)
    at node_modules/.pnpm/supports-color@7.2.0/node_modules/supports-color/index.js (file:///C:/Users/joshua/test/node_modules/vite-plugin-inspect/dist/index.mjs:1156:14)
    at __require2 (file:///C:/Users/joshua/test/node_modules/vite-plugin-inspect/dist/index.mjs:29:44)
    at node_modules/.pnpm/chalk@4.1.2/node_modules/chalk/source/index.js (file:///C:/Users/joshua/test/node_modules/vite-plugin-inspect/dist/index.mjs:1412:56)
    at __require2 (file:///C:/Users/joshua/test/node_modules/vite-plugin-inspect/dist/index.mjs:29:44)
    at file:///C:/Users/joshua/test/node_modules/vite-plugin-inspect/dist/index.mjs:34444:31
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadConfigFromFile (C:\Users\joshua\test\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:68598:31)
```

**Comment by userquin** [comment]
@antfu it seems we are using `chalk` (not `esm` ready), changing to use `kolorist` (the same change we made on `unplugin-icons`)

@josh-hemphill the error also using `vitesse` template repo?

**Comment by josh-hemphill** [comment]
> josh-hemphill the error also using `vitesse` template repo?

I believe so, yes.

**Comment by josh-hemphill** [comment]
Yeah, that's the first error after changing the project type.
Though to get vitesse working I have to do `npm i -D critters@^0.0.10 @vueuse/head@^0.5.1` to get the packages to install.

**Comment by RoenLie** [comment]
Also having this issue when I set my package.json to type:module.
Changing the export statement in vite plugin inspect to js instead of mjs solves the issue on my end and does not seem to cause any side effects.
`"exports": {
  ".": {
	  "require": "./dist/index.js",
	  "import": "./dist/index.js" // changed from mjs to js.
  }
}`

**Comment by emme1444** [comment]
@userquin any updates on this?

**Comment by userquin** [comment]
@emme1444 I'm working on it right now

**Comment by userquin** [comment]
@emme1444 I have it working with `vite + svelte` and `vitesse + type module` + `vitesse + NO type module` (the same project): you can see in action:
- `vite svelte` config here https://imgur.com/OR2wGQD and the inspector here https://imgur.com/sb9pry6
- `vitesse + type module` config here https://imgur.com/yUrqQoI and the inspector here https://imgur.com/GqdkaZ4.
- `vitesse + NO type module` config (undoing previous type module) here https://imgur.com/9S0XFZx and the inspector here https://imgur.com/yutcnQ3.

/cc @antfu PR in a few minutes: some plugins must be used with `.default()`, for example `VueI18n` and `Layouts`  using `vitesse project`.
