### ISSUE TITLE
plugin doesn't work on Windows

### ISSUE THREAD

**Issue by userquin** [antfu/vite-plugin-inspect#2]
While testing something on `unplugin-icons` I just open the plugin to see it, but then: 

![imagen](https://user-images.githubusercontent.com/6311119/133635062-229fae8f-73df-4c8f-8f50-4f41ea176303.png)

The `fetch` api is the originator of the error...

**Comment by userquin** [comment]
@antfu cannot compile the project, I'm trying to fix it, seems you haven't install `vue` dep: ```shell
> vite-plugin-inspect@0.3.6 build:js F:\work\projects\quini\GitHub\antfu\vite-plugin-inspect
> tsup src/node/index.ts --format cjs,esm --dts --env.NODE_ENV production

 CLI  Building entry: src/node/index.ts
 CLI  Using tsconfig: F:\work\projects\quini\GitHub\antfu\vite-plugin-inspect\tsconfig.json
 CLI  tsup v4.14.0
 CLI  Target: node12
 CJS  Build start
 ESM  Build start
 > node_modules/.pnpm/vue-router@4.0.11/node_modules/vue-router/dist/vue-router.cjs.js:10:18: error: Could not resolve "vue" (mark it as external to exclude it from the bundle, or surround it with try/catch to h
andle the failure at run-time)
    10 │ var vue = require('vue');
       ╵                   ~~~~~

 > node_modules/.pnpm/vue-router@4.0.11/node_modules/vue-router/dist/vue-router.cjs.js:10:18: error: Could not resolve "vue" (mark it as external to exclude it from the bundle, or surround it with try/catch to h
andle the failure at run-time)
    10 │ var vue = require('vue');
       ╵                   ~~~~~

 ESM  Build failed
Error: Build failed with 1 error:
node_modules/.pnpm/vue-router@4.0.11/node_modules/vue-router/dist/vue-router.cjs.js:10:18: error: Could not resolve "vue" (mark it as external to exclude it from the bundle, or surround it with try/catch to hand
le the failure at run-time)
    at failureErrorWithLog (F:\work\projects\quini\GitHub\antfu\vite-plugin-inspect\node_modules\.pnpm\esbuild@0.12.17\node_modules\esbuild\lib\main.js:1449:15)
    at F:\work\projects\quini\GitHub\antfu\vite-plugin-inspect\node_modules\.pnpm\esbuild@0.12.17\node_modules\esbuild\lib\main.js:1131:28
    at runOnEndCallbacks (F:\work\projects\quini\GitHub\antfu\vite-plugin-inspect\node_modules\.pnpm\esbuild@0.12.17\node_modules\esbuild\lib\main.js:921:63)
    at buildResponseToResult (F:\work\projects\quini\GitHub\antfu\vite-plugin-inspect\node_modules\.pnpm\esbuild@0.12.17\node_modules\esbuild\lib\main.js:1129:7)
    at F:\work\projects\quini\GitHub\antfu\vite-plugin-inspect\node_modules\.pnpm\esbuild@0.12.17\node_modules\esbuild\lib\main.js:1236:14
    at F:\work\projects\quini\GitHub\antfu\vite-plugin-inspect\node_modules\.pnpm\esbuild@0.12.17\node_modules\esbuild\lib\main.js:609:9
    at handleIncomingPacket (F:\work\projects\quini\GitHub\antfu\vite-plugin-inspect\node_modules\.pnpm\esbuild@0.12.17\node_modules\esbuild\lib\main.js:706:9)
    at Socket.readFromStdout (F:\work\projects\quini\GitHub\antfu\vite-plugin-inspect\node_modules\.pnpm\esbuild@0.12.17\node_modules\esbuild\lib\main.js:576:7)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
 CJS  Build failed
 ERROR  Command failed with exit code 1.
ERROR: "build:js" exited with 1.
 ERROR  Command failed with exit code 1.
```

**Comment by userquin** [comment]
@antfu I think the fix is simple, it is to do just the opposite that we did for `esbuild-node-resolve`: in node you have to keep it, in the client you have to remove it.  On node side just detect windows and add the protocol if absolute (starts with `/`), just remove `file://` (KEEP ONE SLASH TO HANDLE AS ABSOLUTE) on client (`module.vue`).

**Comment by userquin** [comment]
I'll try to test and collect all info so you can just apply the changes I'll send on a PR.

**Comment by userquin** [comment]
@antfu sent to discord

**Comment by userquin** [comment]
@antfu I have it working on local, but modifying the `cjs` on local `pnpm repo`, I need to add it to the branch and make a PR in a few minutes. More info on the PR.
